{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.libxposed",
    "module": "api",
    "version": "100",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "api-100.aar",
          "url": "api-100.aar",
          "size": 16208,
          "sha512": "fcedf21fbfa4c5b65a3ddbe4d613eef1ede45bb507a184d8150258dc00c796dfe8aa745f419c3c886a5a150741f7044fffd0fdd62a76f55901ced00052d82f43",
          "sha256": "2b19e2a33aa1a8808b187c9c6caef43ba9280a108a0b44bb6e729262915da022",
          "sha1": "65e2b904631cf639735ee01b3127f9ffd5b7316c",
          "md5": "fd0444817896f645868327834fe95ab8"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "api-100.aar",
          "url": "api-100.aar",
          "size": 16208,
          "sha512": "fcedf21fbfa4c5b65a3ddbe4d613eef1ede45bb507a184d8150258dc00c796dfe8aa745f419c3c886a5a150741f7044fffd0fdd62a76f55901ced00052d82f43",
          "sha256": "2b19e2a33aa1a8808b187c9c6caef43ba9280a108a0b44bb6e729262915da022",
          "sha1": "65e2b904631cf639735ee01b3127f9ffd5b7316c",
          "md5": "fd0444817896f645868327834fe95ab8"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "api-100-sources.jar",
          "url": "api-100-sources.jar",
          "size": 10244,
          "sha512": "4823fb19b83fab2fcf6de7b9357b3da7407015ec45b7783eb49fab52614c98d327145de3bc4357b6345b82dbe3a622855c0602096ee431636d8ce199f79db5e9",
          "sha256": "725334825579012d8dc678bcfca49e1923ada14a7744e3595e74a8efe8261a65",
          "sha1": "7c41e80d64aed490440c30bb660ab9867c003540",
          "md5": "3674e59f9a64606c70d1ec03235f663c"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseJavaDocPublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "api-100-javadoc.jar",
          "url": "api-100-javadoc.jar",
          "size": 394723,
          "sha512": "8b39f3d28503bd3e8833a7945b486cd3934f0d5d7403cbfb8eab74650fc5472506822c16b7aa1f68f5725a88b5e821eba80493d008e56afdead007d7c196ff0b",
          "sha256": "d841b624f729c88c639667f86828515cc760f2ba96409963e5678a925dd223cb",
          "sha1": "389ba1dcd8ad549a71073ea0eec4731893bbc343",
          "md5": "410d0a0a98c5c46334ae5c09dd4a2f21"
        }
      ]
    }
  ]
}
